plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.helium'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.helium"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // 零第三方依赖，只用 Android SDK 自带的基础类
}
